# Generated by Django 6.0.7 on 2026-08-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='resolvido',
            field=models.BooleanField(default=False),
        ),
    ]
