# Generated by Django 6.0.7 on 2026-07-30 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escopo', models.CharField(choices=[('celula', 'Célula'), ('rede', 'Rede'), ('global', 'Global')], max_length=10)),
                ('conteudo', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('celula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='church.celula')),
                ('posted_as', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_como_celula', to='church.celula')),
                ('rede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='church.rede')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['escopo', '-created_at'], name='posts_post_escopo_3367ac_idx'), models.Index(fields=['celula', '-created_at'], name='posts_post_celula__a93e23_idx'), models.Index(fields=['rede', '-created_at'], name='posts_post_rede_id_401deb_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('celula__isnull', False), ('escopo', 'celula'), ('rede__isnull', True)), models.Q(('celula__isnull', True), ('escopo', 'rede'), ('rede__isnull', False)), models.Q(('celula__isnull', True), ('escopo', 'global'), ('rede__isnull', True)), _connector='OR'), name='post_escopo_alvo'), models.CheckConstraint(condition=models.Q(('posted_as__isnull', True), ('escopo', 'celula'), _connector='OR'), name='post_posted_as_so_celula')],
            },
        ),
    ]
