# Generated by Django 6.0.7 on 2026-08-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_imagem_alter_post_conteudo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
