# Generated by Django 6.0.7 on 2026-07-30 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('cor', models.CharField(choices=[('azul', 'Azul'), ('branca', 'Branca'), ('cinza', 'Cinza'), ('vermelha', 'Vermelha')], max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Rede',
                'verbose_name_plural': 'Redes',
                'ordering': ['cor'],
            },
        ),
        migrations.CreateModel(
            name='Celula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='celulas', to='church.rede')),
            ],
            options={
                'verbose_name': 'Célula',
                'verbose_name_plural': 'Células',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Membro'), ('cell_leader', 'Líder de célula'), ('network_leader', 'Líder de rede'), ('pastor', 'Pastor')], max_length=20)),
                ('celula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='church.celula')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
                ('rede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='church.rede')),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('role__in', ['member', 'cell_leader']), ('celula__isnull', False), ('rede__isnull', True)), models.Q(('role', 'network_leader'), ('celula__isnull', True), ('rede__isnull', False)), models.Q(('role', 'pastor'), ('celula__isnull', True), ('rede__isnull', True)), _connector='OR'), name='membership_role_scope')],
            },
        ),
    ]
